name: Build Lovable UI → frontend/

on:
  push:
    paths:
      - 'lovable-ui/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & build Lovable UI
        working-directory: lovable-ui
        run: |
          npm ci
          npm run build

      - name: Copy to frontend folder
        run: |
          rm -rf frontend/*
          mkdir -p frontend
          cp -R lovable-ui/dist/* frontend/

      - name: Commit built frontend
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: chore: update frontend build from GH Actions
          file_pattern: "frontend/**"
          branch: main
